//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lg.EducationPlatform.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public long Id { get; set; }
        public string SurName { get; set; }
        public byte Sex { get; set; }
        public string Period { get; set; }
        public byte ExaminationLevel { get; set; }
        public string MajorName { get; set; }
        public string Nationality { get; set; }
        public string Birthday { get; set; }
        public string PoliticalStatus { get; set; }
        public byte EducationalLevel { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string TestFreeCondition { get; set; }
        public string Remark { get; set; }
        public string IdCardFrontPath { get; set; }
        public string IdCardBackPath { get; set; }
        public string BareheadedPhotoPath { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public long CreatorUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
